config/routes.rb
Reg::Application.routes.draw do

get "log_out" => "sessions#destroy", :as => "log_out"
get "log_in" => "sessions#new", :as => "log_in"

get "sign_up" => "users#new", :as => "sign_up"
get "edit_user" => "users#edit", :as=> "edit_user"
get "edit_admin" => "admins#edit", :as=> "edit_admin"
get "sign_up_admin" => "admins#new", :as => "sign_up_admin"
delete "/delete_admin/:id" =>"admins#destroy", :as=>"destroy"
delete "/delete/:id" =>"users#destroy", :as=>"destroy"
get "users" => "users#index", :as=> "users"
get "/admins/:id" => "admins#show", :as=> "admin_show"
root :to => "users#new"
resources :super_admins, controller: :admins
resources :just_admins, controller: :admins
resources :users do
  collection {post :sort}
  end
resources :admins do
  collection {post :sort}
  end
resources :sessions

end

app/views/admins/_modal.html.erb
<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" id="myModalLabel">Modal title</h4>
      </div>
      <div class="modal-body">
        <% provide(:title, "Edit user") %>
<h2 id="success"></h2>

<div class="row">
<h1>Update your profile</h1>
  <div class="span6 offset3">
    <%= form_for(@admin)  do |f| %>

      <%= f.label :email %>
      <%= f.text_field :email, "size" => 20 %> </br>

      <%= f.label :password %>
      <%= f.password_field :password %></br>

      <%= f.label :firstname %>
      <%= f.text_field :firstname, "size" => 20 %></br>

      <%= f.label :lastname %>
      <%= f.text_field :lastname, "size" => 20 %></br>

    

  </div>
</div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      
        <%= f.submit "Save changes", class: "btn btn-primary" %>
        <%end%>
      </div>
    </div>
  </div>
</div>
<!-- Modal -->

app/views/admins/_sortable_list.html.erb
<script src="/assets/application.js?body=1" type="text/javascript"></script>
<tr>
  <th><%= sortable "email" %></th>
  <th><%= sortable "firstname" %></th>
<th><%= sortable "lastname" %></th>
<th><%= sortable "created_at" %></th>
</tr>

<ul class="sortable" data-update-url="<%=sort_admins_url%>">
<%@admins.each do |admin|%>
 <%= content_tag_for :li, admin do%>
<%=admin.email%>|
<%=admin.firstname%>
<%=admin.lastname%>
<%=admin.created_at%>


 <%= link_to "Delete", "delete_admin/#{admin.id}", :class => 'delete' %>|
<%end%>


<%end%>
</ul>



<%= will_paginate @admins %>

app/views/admins/edit.html.erb
<% provide(:title, "Edit user") %>
<h2 id="success"></h2>


<div class="row">
<h1>Update your profile</h1>
  <div class="span6 offset3">
    <%= form_for(@admin)  do |f| %>

      <%= f.label :email %>
      <%= f.text_field "email", "size" => 20 %> </br>

      <%= f.label :password %>
      <%= f.password_field :password %></br>

      <%= f.label :firstname %>
      <%= f.text_field "firstname", "size" => 20 %></br>

      <%= f.label :lastname %>
      <%= f.text_field "lastname", "size" => 20 %></br>

      <%= f.submit "Save changes", class: "btn-send" %>
    <% end %>

  </div>
</div>

app/views/admins/index.html.erb
<!Doctype html>
<html>
<head>

</head>
<body>


<%if @admins!=nil%>
<%= form_tag admins_path, :method => 'get', :class => "products_search" do %>
  <p>
    <%= text_field_tag :search, params[:search] %>
    <%= submit_tag "Search", :name => nil %>
  </p>
  <div id="admins"><%= render "admins/sortable_list"%>

  </div>
<% end %>

<% end %>





</body>
</html>

app/views/admins/index.js.erb
$("#admins").html("<%= escape_javascript(render("admins/sortable_list")) %>");

app/views/admins/new.html.erb
<h1>Sign Up</h1>

<%= form_for(@admin) do |f| %>
  <% if @admin.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% for message in @admin.errors.full_messages %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <p>
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </p>
  <p>
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </p>
  <p>
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation %>
  </p>
  <p>
    <%= f.label :Super? %><br />
    <%= f.check_box :checkbox %>
  </p>
  <p class="button"><%= f.submit %></p>
<% end %>

app/views/admins/show.html.erb
<% provide(:title, "Edit user") %>
<h2 id="success"></h2>
<script language="javascript" type="text/javascript" src="update.js.erb"></script>

<div class="row">
<h1>Your file</h1>
  <div class="span6 offset3">
    <p>Your name is <%=@admin.firstname%></p>
    <p>Your surname is <%=@admin.lastname%></p>
   <p> Your email is <%=@admin.email%></p>
    <button class="btn btn-primary btn" data-toggle="modal" data-target="#myModal" id="button">
  Edit admin
</button>
<%= render "admins/modal"%>
  </div>
</div>