config/routes.rb
Reg::Application.routes.draw do

get "log_out" => "sessions#destroy", :as => "log_out"
get "log_in" => "sessions#new", :as => "log_in"

get "sign_up" => "users#new", :as => "sign_up"
get "edit_user" => "users#edit", :as=> "edit_user"
get "edit_admin" => "admins#edit", :as=> "edit_admin"
get "sign_up_admin" => "admins#new", :as => "sign_up_admin"
delete "/delete_admin/:id" =>"admins#destroy", :as=>"destroy"
delete "/delete/:id" =>"users#destroy", :as=>"destroy"
get "users" => "users#index", :as=> "users"
get "/admins/:id" => "admins#show", :as=> "admin_show"
root :to => "users#new"
resources :super_admins, controller: :admins
resources :just_admins, controller: :admins
resources :users do
  collection {post :sort}
  end
resources :admins do
  collection {post :sort}
  end
resources :sessions

end

app/models/user.rb
class User < ActiveRecord::Base
  
  attr_accessible :email, :password, :password_confirmation, :firstname, :lastname
 attr_accessor :password
 
  before_save :encrypt_password 
  before_update :encrypt_password
  validates_confirmation_of :password
  validates_presence_of :password, :on => :create
  validates_presence_of :email
  validates_uniqueness_of :email
  
 include ModelMethods
 
  searchable do
    text :email, :firstname
  end

 def is_User?
     true
  end
   def is_Super?
     false
  end

def is_Just?
     false
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
   helper_method :sort_column, :sort_direction

def new
  @user = User.new
end

def create
  @user = User.new(params[:user])
  if @user.save
    redirect_to root_url, :notice => "Signed up!"
  else
    render "new"
  end
end

def edit
  @user = User.find(session[:user_id])
end

def show
  @user = User.find(session[:user_id])
end


def update
 	   @person = User.find(session[:user_id])
   if @person.update_attributes(params[:user])
      redirect_to user_url, :notice => "Updated"
   else
      render 'edit'
  end
end
  
def destroy
    @user=User.find(params[:id])
    @user.destroy
   true
end

def index
    
    #@users = User.order('position ASC').paginate(:page => params[:page],per_page: 4)
    #@users = User.search(params[:search]).order(sort_column + " " + sort_direction).paginate(:per_page => 5, :page => params[:page])
@search = User.search do
  fulltext params[:search]
end
@users=@search.results
end

def sort
  params[:user].each_with_index do |id, index|
     User.update_all({position: index+1}, {id: id})
  end
  render true
end
  
  private
  
  def sort_column
    User.column_names.include?(params[:sort]) ? params[:sort] : "position"
  end
  
  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_modal.html.erb
<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" id="myModalLabel">Modal title</h4>
      </div>
      <div class="modal-body">
        <% provide(:title, "Edit user") %>
<h2 id="success"></h2>

<div class="row">
<h1>Update your profile</h1>
  <div class="span6 offset3">
    <%= form_for(@user)  do |f| %>

      <%= f.label :email %>
      <%= f.text_field "email", "size" => 20 %> </br>

      <%= f.label :password %>
      <%= f.password_field :password %></br>

      <%= f.label :firstname %>
      <%= f.text_field "firstname", "size" => 20 %></br>

      <%= f.label :lastname %>
      <%= f.text_field "lastname", "size" => 20 %></br>

    

  </div>
</div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      
        <%= f.submit "Save changes", class: "btn btn-primary" %>
        <%end%>
      </div>
    </div>
  </div>
</div>
<!-- Modal -->

app/views/users/_sortable_list.html.erb
<script src="/assets/application.js?body=1" type="text/javascript"></script>
<tr>
  <th><%= sortable "email" %></th>
  <th><%= sortable "firstname" %></th>
<th><%= sortable "lastname" %></th>
<th><%= sortable "created_at" %></th>
</tr>

<ul class="sortable" data-update-url="<%=sort_users_url%>">
<%@users.each do |user|%>
 <%= content_tag_for :li, user do%>
<%=user.email%>|
<%=user.firstname%>
<%=user.lastname%>
<%=user.created_at%>


 <%= link_to "Delete", "delete/#{user.id}", :class => 'delete' %>|
<%end%>


<%end%>
</ul>



<%= will_paginate @users %>

app/views/users/edit.html.erb
<% provide(:title, "Edit user") %>
<h2 id="success"></h2>
<script language="javascript" type="text/javascript" src="update.js.erb"></script>

<div class="row">
<h1>Update your profile</h1>
  <div class="span6 offset3">
    <%= form_for(@user)  do |f| %>

      <%= f.label :email %>
      <%= f.text_field "email", "size" => 20 %> </br>

      <%= f.label :password %>
      <%= f.password_field :password %></br>

      <%= f.label :firstname %>
      <%= f.text_field "firstname", "size" => 20 %></br>

      <%= f.label :lastname %>
      <%= f.text_field "lastname", "size" => 20 %></br>

      <%= f.submit "Save changes", class: "btn-send" %>
    <% end %>

  </div>
</div>

app/views/users/index.html.erb
<!Doctype html>
<html>
<head>

</head>
<body>


<%if @users!=nil%>
<%= form_tag users_path, :method => 'get', :class => "products_search" do %>
  <p>
    <%= text_field_tag :search, params[:search] %>
    <%= submit_tag "Search", :name => nil %>
  </p>

  <div id="users"><%= render "users/sortable_list"%>

  </div>
<% end %>

<% end %>









</body>
</html>

app/views/users/index.js.erb
$("#users").html("<%= escape_javascript(render("users/sortable_list")) %>");

app/views/users/new.html.erb
<%= form_for(@user, html: { id: "signup" })  do |f| %>
<h1>Start your registration right now</h1>
  <% if @user.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% for message in @user.errors.full_messages %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <p>

    <%= f.text_field :email,  placeholder:  "example@email.com", required:""%>
  </p>
  <p>
 
    <%= f.password_field :password,  placeholder:  "Choose your password", required:"" %>
  </p>
  <p>
  
    <%= f.password_field :password_confirmation,  placeholder:  "Confirm password", required:"" %>
  </p>
  <p class="button"><%= f.submit :class => "btn btn-lg btn-primary btn-block" %></p>
<% end %>
<a href="/log_in" class="text-center new-account">Sign in</a>

app/views/users/show.html.erb
<% provide(:title, "Edit user") %>
<h2 id="success"></h2>
<script language="javascript" type="text/javascript" src="update.js.erb"></script>

<div class="row">
<h1>Your file</h1>
  <div class="span6 offset3">
    <p>Your name is <%=@user.firstname%></p>
    <p>Your surname is <%=@user.lastname%></p>
   <p> Your email is <%=@user.email%></p>
    
  </div>
</div>

app/views/users/update.js.erb
$(document).ready(function(){
$('.row').remove();
$('#success').append('Updated');
alert('assa');
}); 