config/routes.rb
Reg::Application.routes.draw do

get "log_out" => "sessions#destroy", :as => "log_out"
get "log_in" => "sessions#new", :as => "log_in"

get "sign_up" => "users#new", :as => "sign_up"
get "edit_user" => "users#edit", :as=> "edit_user"
get "edit_admin" => "admins#edit", :as=> "edit_admin"
get "sign_up_admin" => "admins#new", :as => "sign_up_admin"
delete "/delete_admin/:id" =>"admins#destroy", :as=>"destroy"
delete "/delete/:id" =>"users#destroy", :as=>"destroy"
get "users" => "users#index", :as=> "users"
get "/admins/:id" => "admins#show", :as=> "admin_show"
root :to => "users#new"
resources :super_admins, controller: :admins
resources :just_admins, controller: :admins
resources :users do
  collection {post :sort}
  end
resources :admins do
  collection {post :sort}
  end
resources :sessions

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title></title>
  <%= javascript_include_tag "application"%>
  <%= stylesheet_link_tag 'application' %>
 
</head>


<body>
<div id="user_nav">
  <% if current_user %>

    Logged in as <%= current_user.email %>.
    <%= link_to "Log out", log_out_path ,:class => 'btn btn-primary'%>
    <!-- Button trigger modal -->
<button class="btn btn-primary " data-toggle="modal" data-target="#myModal">
  Edit user
</button>
    <!-- Button trigger modal -->
<%= render "users/modal"%>



  <% elsif current_admin %>

    Logged in as <%= current_admin.email %>.
    <%= link_to "Log out", log_out_path,:class => 'btn btn-primary' %>
     <!-- Button trigger modal -->

<%= link_to "Profile", "/admins/#{current_admin.id}" ,:class => 'btn btn-primary' %>


    <!-- Button trigger modal -->


  <%if current_admin.type=="SuperAdmin"%>
    <%= link_to "Add_admin", sign_up_admin_path ,:class => 'btn btn-primary'%>
   <%end%>
 
  <% end %>
</div>

<% flash.each do |name, msg| %>
  <%= content_tag :div, msg, :id => "flash_#{name}" %>
<% end %>

<%=yield%>
</body>
</html>